const inter = Inter({ subsets: ["latin"] });
import { Inter } from "next/font/google";
import styles from "./Layout.module.css";
import Head from "next/head";
import DenseAppBar from "./AppBar";
import Sidebar from "./Sidebar";

type LayoutProps = {
  children: React.ReactNode;
  title: string;
};
export const MainLayout = ({ children, title }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <DenseAppBar />
        <Sidebar />
        {children}
      </main>
    </>
  );
};
